import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "fs";
import path from "path";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const outfile = "C:\\Users\\chanmin.park\\OneDrive - LG전자\\.obsidian\\plugins\\obsidian-chanmin-plugin\\main.js";
const outdir = path.dirname(outfile);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: outfile,
	minify: prod,
	plugins: [
		{
			name: "copy-manifest",
			setup(build) {
				build.onEnd(() => {
					try {
						if (!fs.existsSync(outdir)) {
							fs.mkdirSync(outdir, { recursive: true });
						}
						fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
						if (fs.existsSync("styles.css")) {
							fs.copyFileSync("styles.css", path.join(outdir, "styles.css"));
						}
						console.log("Successfully copied manifest.json and styles.css to " + outdir);
					} catch (e) {
						console.error("Failed to copy manifest.json or styles.css", e);
					}
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
